import {createClient} from "@supabase/supabase-js";
const SUPABASE_URL="https://tnlsbwdzfvjaouufkzhi.supabase.co";
const SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRubHNid2R6ZnZqYW91dWZremhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3OTU0NTEsImV4cCI6MjA2MTM3MTQ1MX0.YBbBK6tOFyWVC8yar4CAbTENOiQ6IgMw-MTG4gVEwhI";
export const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);